# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Evaluation problem - Forward algorithm
#' 
#' @param A initial transition probability
#' @param B initial observation probability
#' @param P initial probability distribution
#' @param O observation sequence
#' @return Observation sequence probability
EvaluationForward <- function(A, B, P, O) {
    .Call(`_hmm_EvaluationForward`, A, B, P, O)
}

#' Evaluation problem - Backward algorithm
#' 
#' @param A initial transition probability
#' @param B initial observation probability
#' @param P initial probability distribution
#' @param O observation sequence
#' @return Observation sequence probability
EvaluationBackward <- function(A, B, P, O) {
    .Call(`_hmm_EvaluationBackward`, A, B, P, O)
}

LearningForward <- function(A, B, PI, O) {
    .Call(`_hmm_LearningForward`, A, B, PI, O)
}

LearningBackward <- function(A, B, PI, O) {
    .Call(`_hmm_LearningBackward`, A, B, PI, O)
}

#' Model parameter learning - Baum-Welch Algorithm - PI
#' 
#' @param A initial transition probability
#' @param B initial observation probability
#' @param PI initial probability distribution
#' @param O observation sequence
#' @param e threshold value
#' @return PI parameter estimation
LearnBaumWelch_PI <- function(A, B, PI, O, e = 0.05) {
    .Call(`_hmm_LearnBaumWelch_PI`, A, B, PI, O, e)
}

#' Model parameter learning - Baum-Welch Algorithm - A
#' 
#' @param A initial transition probability
#' @param B initial observation probability
#' @param PI initial probability distribution
#' @param O observation sequence
#' @param e threshold value
#' @return A parameter estimation
LearnBaumWelch_A <- function(A, B, PI, O, e = 0.05) {
    .Call(`_hmm_LearnBaumWelch_A`, A, B, PI, O, e)
}

#' Model parameter learning - Baum-Welch Algorithm - B
#' 
#' @param A initial transition probability
#' @param B initial observation probability
#' @param PI initial probability distribution
#' @param O observation sequence
#' @param e threshold value
#' @return B parameter estimation
LearnBaumWelch_B <- function(A, B, PI, O, e = 0.05) {
    .Call(`_hmm_LearnBaumWelch_B`, A, B, PI, O, e)
}

#' Prediction problem - Viterbi Algorithm
#' 
#' @param A initial transition probability
#' @param B initial observation probability
#' @param PI initial probability distribution
#' @param V observation set
#' @param Q state set
#' @param O observation sequence
#' @return Optimal path
Viterbi_cpp <- function(A, B, PI, V, Q, obs) {
    .Call(`_hmm_Viterbi_cpp`, A, B, PI, V, Q, obs)
}

